import type { Metadata } from "next";
import { Inter, Space_Grotesk } from "next/font/google";
import CustomCursor from "./components/ui/CustomCursor/CustomCursor";
import FloatingScrollbar from "./components/ui/FloatingScrollbar/FloatingScrollbar";

import "./globals.css";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-body",
  display: "swap",
});

const spaceGrotesk = Space_Grotesk({
  subsets: ["latin"],
  variable: "--font-heading",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${inter.variable} ${spaceGrotesk.variable} has-floating-scrollbar`}
    >
      <body className="min-h-full flex flex-col"> 
        <CustomCursor />
        <FloatingScrollbar />
        {children}
        </body>
    </html>
  );
}
